name: json-api
version: '0.1.4.0'
synopsis: Utilities for generating JSON-API payloads
description: ! 'Provides utilities for deriving JSON payloads conformant to the json-api specification'
category: Network
author: Todd Mohney
maintainer: Todd Mohney <toddmohney@gmail.com>
copyright: 2016 Todd Mohney
license: MIT
github: toddmohney/json-api.git

extra-source-files:
- README.md
- LICENSE
- circle.yml
- stack.yaml
- example/LICENSE
- example/README.md
- example/example.cabal
- example/*.hs
- example/stack.yaml

default-extensions:
- DeriveGeneric
- GeneralizedNewtypeDeriving
- OverloadedStrings
- RecordWildCards

ghc-options:
- -Wall
- -Wcompat
# - -Werror
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -fhide-source-paths
- -fno-warn-warnings-deprecations
- -freverse-errors
- -fwarn-unused-binds
- -fwarn-unused-imports
- -fwarn-unused-matches

dependencies:
- aeson
- base >=4.7 && <5.0
- containers
- data-default
- deepseq
- lens
- lens-aeson
- text
- unordered-containers
- url

library:
  source-dirs: src
  default-extensions:
  - TemplateHaskell
  ghc-options:
  - -fwarn-unused-imports
  exposed-modules:
  - Network.JSONApi
  - Network.JSONApi.Error
  - Network.JSONApi.Document
  - Network.JSONApi.Identifier
  - Network.JSONApi.Meta
  - Network.JSONApi.Link
  - Network.JSONApi.Resource
  - Network.JSONApi.Pagination
  - Network.JSONApi.Source

tests:
  json-api-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - aeson-pretty
    - bytestring
    - hspec
    - json-api
    verbatim:
      build-tool-depends:
        hspec-discover:hspec-discover
stability: experimental
tested-with: ghc ==7.10.3
